name: endpoint tests 

on:
  push:
    branches: [ "feature-endpoint-testing" ]
  pull_request:
    branches: [ "feature-endpoint-testing" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  
                            
    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Copy database from DbTemplate to Backend
    - name: Copy database to project
      run: copy DbTemplate\\_db.sqlite3 Backend

    # Start backend non-blocking
    - name: Start the backend
      run: cd Backend && dotnet run &

    # Ping the server
    - name: Ping the server
      run: ping http://127.0.0.1:3001

    # Ping the server
    - name: Ping the server
      run: ping http://localhost:3001