name: UI tests

on:
  push:
    branches: [ "feature-ui-testing" ]
  pull_request:
    branches: [ "feature-ui-testing" ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Copy database to project
      run: Copy-Item DbTemplate\\_db.sqlite3 Backend

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Cypress
      run: |
        cd ui-tests
        npm install

    - name: Start the backend
      run: |
        cd Backend
        Start-Process -FilePath dotnet -ArgumentList 'run' -NoNewWindow -PassThru

    - name: Wait for backend to be ready
      run: |
        $timeout = 120
        $timer = 0
        while ($timer -lt $timeout) {
          try {
            $response = Invoke-WebRequest -Uri http://localhost:3001 -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "Backend is ready"
              break
            }
          } catch {
            Write-Host "Waiting for backend..."
          }
          Start-Sleep -Seconds 5
          $timer += 5
        }
        if ($timer -ge $timeout) {
          Write-Error "Backend did not start in time"
          exit 1
        }

    - name: Run the endpoint tests
      run: |
        cd ui-tests
        npx wait-on http://localhost:3001
        npm run test-ui-cli