name: UI tests

on:
  push:
    branches: [ "feature-ui-testing" ]
  pull_request:
    branches: [ "feature-ui-testing" ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Copy database to project
      run: |
        Copy-Item DbTemplate\\_db.sqlite3 Backend

    - name: Install Cypress
      run: |
        cd ui-tests
        npm install

    - name: Start the backend
      shell: bash
      run: |
        cd Backend
        nohup dotnet run > output.log 2>&1 &

    - name: Wait for backend to be ready
      shell: bash
      run: |
        timeout=120
        timer=0
        while [[ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:3001)" != "200" ]]; do
          if [ $timer -ge $timeout ]; then
            echo "Backend did not start in time"
            cat Backend/output.log
            exit 1
          fi
          echo "Waiting for backend..."
          sleep 5
          timer=$((timer + 5))
        done
        echo "Backend is ready"

    - name: Run the endpoint tests
      shell: bash
      run: |
        cd ui-tests
        npx wait-on http://localhost:3001
        npm run test-ui-cli