name: UI tests 

on:
  push:
    branches: [ "feature-ui-testing" ]
  pull_request:
    branches: [ "feature-ui-testing" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  
                            
    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache and install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Copy database from DbTemplate to Backend
    - name: Copy database to project
      run: copy DbTemplate\\_db.sqlite3 Backend

    - name: Install cypress
      run: cd ui-tests && npm install

    # Start backend non-blocking
    - name: Start the backend
      shell: bash
      run: cd Backend && nohup dotnet run & 

    # Run the endpoint tests
    - name: Run the endpoint tests
      run: cd ui-tests && npm run test-ui-cli 