name: Unit, endpoints and UI-testing 

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  
                            
    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend
  
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Cache and install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Install Cypress & save to cache
    - name: Install Cypress
      uses: cypress-io/github-action@v6
      with:
        working-directory: ui-tests
        build: npm install
        runTests: false

    # Copy database from DbTemplate to Backend
    - name: Copy database to project
      run: copy DbTemplate\\_db.sqlite3 Backend

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "console;verbosity=detailed"
    
    # Start backend non-blocking
    - name: Start the backend
      shell: bash
      run: cd Backend && nohup dotnet run & 

    # Run the endpoint tests
    - name: Run the endpoint tests
      run: cd endpoint-tests && npm test

    # Run the UI tests
    - name: Run the UI tests
      run: cd ui-tests && npm run test-ui-cli
      